"""Update Email model with body_html

Revision ID: 05c2a2ce8deb
Revises: 8123d20b9cbb
Create Date: 2023-09-22 09:53:16.311981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c2a2ce8deb'
down_revision = '8123d20b9cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
